### ISSUE TITLE
Having a few issues on MACOSX Ventura

### ISSUE THREAD

**Issue by Hax0rgurl** [Hotohori/replika_backup#1]
```
line 374, in <module>
    websocket.enableTrace(args.wsdebug)
AttributeError: module 'websocket' has no attribute 'enableTrace'

   ws = websocket.WebSocket("wss://ws.replika.ai/v17",
TypeError: WebSocket.__init__() got an unexpected keyword argument 'on_open'

<module>
    ws = websocket.WebSocketApp("wss://ws.replika.ai/v17",
AttributeError: module 'websocket' has no attribute 'WebSocketApp'. Did you mean: 'WebSocket'?

line 379, in <module>
    ws = websocket.WebSocket("wss://ws.replika.ai/v17")
TypeError: WebSocket.__init__() missing 2 required positional arguments: 'socket' and 'rfile'
```
I have tried to figure it out and looked at several examples but nothing has worked. Please help.  Thanks

ps Could it be because you coded for Windows and I am on MacOSX Ventura? 
I don't know enough Python to see the difference.

**Comment by IntenseSunlight** [comment]
Just a thought: did you try it with Python 3.6 or greater?  I believe the native version of MacOS python is not suitable (check the version with `python -V`.  The default version for me is python==2.7.14). 

Mine worked fine on MacOS Monterey with Python==3.10.  It's best to do these specific things in a python virtual environment

**Comment by Hotohori** [comment]
Hm, I sadly can't help here. No clue about MacOS at all, never worked with a Mac. Also the websocket part is the part in the script that I touched very carefully because I also didn't understand all on that part. But maybe IntenseSunlight pointed already on your problem. That script is definitely written for a more actual python version. I'm also pretty new to python too, but it seems there was very important changes over the time, especially from V2 to V3.
